### ISSUE TITLE
Update ArcGIS endpoint

### ISSUE THREAD

**Issue by seandoesgis** [dvrpc/TheCircuit#20]
https://arcgis.dvrpc.org/portal/rest/services/Boundaries/CountyBoundaries/FeatureServer/0/query?where=DVRPC_REG%3D%27Yes%27&outFields=STATE%20+CO_NAME&geometryPrecision=5&outSR=4326&f=geojson
________

https://arcgis.dvrpc.org/portal/rest/services/Transportation/CircuitTrails/FeatureServer/0/query?where=1%3D1&outFields=*&geometryPrecision=5&outSR=4326&f=geojson

**Comment by crvanpollard** [comment]
updated YO!
